# Read the Docs configuration file for MkDocs projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 1

# Set the version of Python and other tools you might need
build:
  os: Windows 11
  tools:
    python: "3.11.6"

mkdocs:
  configuration: mkdocs.yml
